M48
; DRILL file {KiCad (6.0.0)} date Sat Aug  6 06:41:07 2022
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-08-06T06:41:07-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X85.005Y-50.845
X85.005Y-113.075
X173.905Y-50.845
X173.905Y-113.075
T0
M30
