M48
; DRILL file {KiCad (6.0.0)} date Fri Aug  5 10:14:31 2022
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-08-05T10:14:31-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.450
%
G90
G05
T1
X99.187Y-153.797
X117.348Y-119.761
X135.509Y-153.797
T2
X111.369Y-150.36
X122.799Y-150.36
T0
M30
